database: /path/to/sqlite.db
file_extensions:
    - 'md'
    - 'htm'
    - 'html'
    - 'txt'
base_url: https://www.example.com
# Note: "Search engines adopting the IndexNow protocol agree that submitted URLs will be automatically shared with all other participating search engines."
# Source: https://www.indexnow.org/documentation
#
# At the time of writing IndexNow participants are:
#  - https://www.bing.com/indexnow
#  - https://yandex.com/indexnow
#  - https://search.seznam.cz/indexnow
submit: https://yandex.com/indexnow
